# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
# curl --data-binary @.github/codecov.yml https://codecov.io/validate

codecov:
  strict_yaml_branch: main  # only use the latest YAML on stated branch

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false      # Post comment even if there's no change in coverage
  require_base: false         # [true :: must have a base report to post]
  require_head: true           # [true :: must have a head report to post]
  hide_project_coverage: true # [true :: only show coverage on the git diff]

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
  individual_components:
    - component_id: http
      name: http
      paths:
        - http/**


# https://app.codecov.io/gh/ifnotnil/x/flags/main
# https://docs.codecov.com/docs/commit-status
# https://docs.codecov.com/docs/components
# https://docs.codecov.com/docs/flags
