# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[github-actions]"

  - package-ecosystem: "gomod"
    directory: "/tools"
    allow:
      - dependency-type: direct
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[tools]"
      include: "scope"
    groups:
      all-tools:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/http"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[deps][http]"
      include: "scope"
