// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package id

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockencoding creates a new instance of mockencoding. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockencoding(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockencoding {
	mock := &mockencoding{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockencoding is an autogenerated mock type for the encoding type
type mockencoding struct {
	mock.Mock
}

type mockencoding_Expecter struct {
	mock *mock.Mock
}

func (_m *mockencoding) EXPECT() *mockencoding_Expecter {
	return &mockencoding_Expecter{mock: &_m.Mock}
}

// appendEncode provides a mock function for the type mockencoding
func (_mock *mockencoding) appendEncode(dst []byte, src []byte) []byte {
	ret := _mock.Called(dst, src)

	if len(ret) == 0 {
		panic("no return value specified for appendEncode")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) []byte); ok {
		r0 = returnFunc(dst, src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// mockencoding_appendEncode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'appendEncode'
type mockencoding_appendEncode_Call struct {
	*mock.Call
}

// appendEncode is a helper method to define mock.On call
//   - dst []byte
//   - src []byte
func (_e *mockencoding_Expecter) appendEncode(dst interface{}, src interface{}) *mockencoding_appendEncode_Call {
	return &mockencoding_appendEncode_Call{Call: _e.mock.On("appendEncode", dst, src)}
}

func (_c *mockencoding_appendEncode_Call) Run(run func(dst []byte, src []byte)) *mockencoding_appendEncode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockencoding_appendEncode_Call) Return(bytes []byte) *mockencoding_appendEncode_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *mockencoding_appendEncode_Call) RunAndReturn(run func(dst []byte, src []byte) []byte) *mockencoding_appendEncode_Call {
	_c.Call.Return(run)
	return _c
}

// decode provides a mock function for the type mockencoding
func (_mock *mockencoding) decode(dst []byte, src []byte) (int, error) {
	ret := _mock.Called(dst, src)

	if len(ret) == 0 {
		panic("no return value specified for decode")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) (int, error)); ok {
		return returnFunc(dst, src)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, []byte) int); ok {
		r0 = returnFunc(dst, src)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = returnFunc(dst, src)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockencoding_decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'decode'
type mockencoding_decode_Call struct {
	*mock.Call
}

// decode is a helper method to define mock.On call
//   - dst []byte
//   - src []byte
func (_e *mockencoding_Expecter) decode(dst interface{}, src interface{}) *mockencoding_decode_Call {
	return &mockencoding_decode_Call{Call: _e.mock.On("decode", dst, src)}
}

func (_c *mockencoding_decode_Call) Run(run func(dst []byte, src []byte)) *mockencoding_decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockencoding_decode_Call) Return(n int, err error) *mockencoding_decode_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockencoding_decode_Call) RunAndReturn(run func(dst []byte, src []byte) (int, error)) *mockencoding_decode_Call {
	_c.Call.Return(run)
	return _c
}

// encodedLen provides a mock function for the type mockencoding
func (_mock *mockencoding) encodedLen(n int) int {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for encodedLen")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// mockencoding_encodedLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'encodedLen'
type mockencoding_encodedLen_Call struct {
	*mock.Call
}

// encodedLen is a helper method to define mock.On call
//   - n int
func (_e *mockencoding_Expecter) encodedLen(n interface{}) *mockencoding_encodedLen_Call {
	return &mockencoding_encodedLen_Call{Call: _e.mock.On("encodedLen", n)}
}

func (_c *mockencoding_encodedLen_Call) Run(run func(n int)) *mockencoding_encodedLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockencoding_encodedLen_Call) Return(n1 int) *mockencoding_encodedLen_Call {
	_c.Call.Return(n1)
	return _c
}

func (_c *mockencoding_encodedLen_Call) RunAndReturn(run func(n int) int) *mockencoding_encodedLen_Call {
	_c.Call.Return(run)
	return _c
}
