#!/usr/bin/env bash

cat <<END >./.github/dependabot.yml
# yaml-language-server: \$schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[github-actions]"

  - package-ecosystem: "gomod"
    directory: "/tools"
    allow:
      - dependency-type: direct
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[tools]"
      include: "scope"
    groups:
      main:
        patterns:
          - "*"
END

section() {
  cat <<END >>./.github/dependabot.yml

  - package-ecosystem: "gomod"
    directory: "/${1}"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[${1}]"
      include: "scope"
    allow:
      - dependency-type: all
    groups:
      main:
        patterns:
          - "*"
END
}
export -f section

./scripts/foreach-mod section
