#!/usr/bin/env bash

# https://man7.org/linux/man-pages/man1/find.1.html
# https://linux.die.net/man/1/find
# https://ss64.com/mac/find.html

# set -e
# set -u
# set -o pipefail

VERBOSE=${VERBOSE:="0"}

__find() {
  find . -type f \
    -and \( -not -path './.git/*' \) \
    -and \( -not -path './.tools/*' \) \
    -and \( -not -path './tools/*' \) \
    -and \( -name go.mod \) | sed -e 's|^\./||' -e 's|/go\.mod$||' | sort
}

# -d delim	Use DELIM to terminate lines, instead of newline
# -t	Remove a trailing DELIM from each line read (default newline)
mapfile -t modules < <(
  __find
)

status=0

for mod in "${modules[@]}"; do
  [[ ${VERBOSE} == "1" ]] && echo "${*} ${mod}"
  "${@}" "${mod}" || status=1
done

exit ${status}
