#!/usr/bin/env bash

# -d delim	Use DELIM to terminate lines, instead of newline
# -t	Remove a trailing DELIM from each line read (default newline)
mapfile -t mod_dirs < <(
  find . -type f \
    -and \( -not -path './.git/*' \) \
    -and \( -not -path './.tools/*' \) \
    -and \( -name go.mod \) | sed -e 's|^\./||' -e 's|/go\.mod$||' | sort | grep -v -e '^tools'
)

go work init

for mod_dir in "${mod_dirs[@]}"; do
  echo ">>> use ${mod_dir}"
  go work use ./"${mod_dir}"
done

go work use ./tools

go work sync
