# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Main CI

on:
  push:
    branches: [ main ]

jobs:

  tools:
    name: Tools
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-go/
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        check-latest: true
        cache: false

    - id: tools
      uses: ./.github/actions/tools

  scripts:
    name: Lints scripts
    needs: [ "tools" ]
    uses: ./.github/workflows/scripts.yml

  http:
    name: HTTP
    needs: [ "tools" ]
    uses: ./.github/workflows/mod_http.yml
