# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Test

on:
  workflow_call:
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      mod_path:
        description: 'Module path'
        required: true
        type: string
        # example: http
    secrets:
      CODECOV_TOKEN:
        description: 'Codecov token'
        required: true

jobs:

  test:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        go-ver: [ "1.23", "1.24" ]
    name: Go Test
    runs-on: "${{ matrix.os }}"
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-go/
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # go-version-file: ./http/go.mod
          go-version: "${{ matrix.go-ver }}.x"
          check-latest: true
          cache: false
          # cache: true
          # cache-dependency-path: ./http/go.sum

      - name: go test
        shell: bash
        working-directory: ${{ inputs.mod_path }}
        run: |
          go test -timeout 60s -race -tags='$(TAGS)' -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.go-ver == '1.24' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ifnotnil/x
          files: ./${{ inputs.mod_path }}/coverage.txt
          codecov_yml_path: ./codecov.yml
