# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: conf

on:
  workflow_dispatch: {}

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    paths:
      - conf/**
      - .github/workflows/sub_conf.yml
      - .golangci.yml
      - tools/**
      - .github/workflows/ci.yml

jobs:

  ci:
    uses: ./.github/workflows/ci.yml
    with:
      mod_path: conf
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
