# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: http

on:
  workflow_dispatch: {}

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
    paths:
      - http/**
      - .github/workflows/http.yml
      - .golangci.yml
      - tools/**

jobs:

  http_lint:
    uses: ./.github/workflows/go_lint.yml
    with:
      path: ./http

  http_test:
    uses: ./.github/workflows/go_test.yml
    with:
      mod_path: http
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
